export enum Scale {
  Diatonic = 'Diatonic',
  SoftChromatic = 'SoftChromatic',
  HardChromatic = 'HardChromatic',
  EnharmonicGa = 'EnharmonicGa',
  EnharmonicZo = 'EnharmonicZo',
  EnharmonicZoHigh = 'EnharmonicZoHigh',
  EnharmonicVou = 'EnharmonicVou',
  EnharmonicVouHigh = 'EnharmonicVouHigh',
  Zygos = 'Zygos',
  Spathi = 'Spathi',
  SpathiGa = 'SpathiGa',
  Kliton = 'Kliton',
}

export enum ScaleNote {
  ZoLow = 'ZoLow',
  NiLow = 'NiLow',
  PaLow = 'PaLow',
  VouLow = 'VouLow',
  GaLow = 'GaLow',
  ThiLow = 'ThiLow',
  KeLow = 'KeLow',
  Zo = 'Zo',
  Ni = 'Ni',
  Pa = 'Pa',
  Vou = 'Vou',
  Ga = 'Ga',
  Thi = 'Thi',
  Ke = 'Ke',
  ZoHigh = 'ZoHigh',
  NiHigh = 'NiHigh',
  PaHigh = 'PaHigh',
  VouHigh = 'VouHigh',
  GaHigh = 'GaHigh',
  ThiHigh = 'ThiHigh',
  KeHigh = 'KeHigh',
}
