export enum TestFileType {
  FthoraTop = 'FthoraTop',
  FthoraBottom = 'FthoraBottom',
  MartyriaFthora = 'MartyriaFthora',
  Gorgon = 'Gorgon',
  Klasma = 'Klasma',
  Hapli = 'Hapli',
  Accidentals = 'Accidentals',
  Expressions = 'Expressions',
  Measures = 'Measures',
  NoteIndicators = 'NoteIndicators',
  Ison = 'Ison',
  ModeKey = 'ModeKey',
  Random = 'Random',
  DropCaps = 'DropCaps',
}
