import { Fthora, ModeSign, QuantitativeNeume } from '@/models/Neumes';

import type { ModelSelector } from './NeumeI18nMappings';
import { Scale, ScaleNote } from './Scales';

export interface ModeKeyTemplate {
  id: number;
  mode: number;
  scale: Scale;
  scaleNote: ScaleNote;
  fthora?: Fthora;
  description: ModelSelector;

  // Visual representation
  martyria: ModeSign;
  note?: ModeSign;
  note2?: ModeSign;
  fthoraAboveNote?: Fthora;
  fthoraAboveNote2?: Fthora;
  fthoraAboveQuantitativeNeumeRight?: Fthora;
  quantitativeNeumeAboveNote?: ModeSign;
  quantitativeNeumeAboveNote2?: ModeSign;
  quantitativeNeumeRight?: QuantitativeNeume;
  optionalFthoras?: {
    fthoraAboveNote?: Fthora;
  };
}

export const modeKeyTemplates: ModeKeyTemplate[] = [
  {
    id: 100,
    mode: 1,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Pa,
    description: ($) => $.model.initialMartyria.heirmologicAndSticheraric,
    martyria: ModeSign.AlphaWithDeltaHat,
    note: ModeSign.Pa,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicPa_Top,
    },
  },
  {
    id: 101,
    mode: 1,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ke,
    description: ($) =>
      $.model.initialMartyria.tetraphonicPapadicAndOldSticheraric,
    martyria: ModeSign.AlphaWithDeltaHat,
    note: ModeSign.Ke,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicKe_Top,
    },
  },
  {
    id: 102,
    mode: 1,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ke,
    description: ($) => $.model.initialMartyria.tetraphonic,
    martyria: ModeSign.AlphaWithDeltaHat,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusHypsiliRight,
  },
  {
    id: 103,
    mode: 1,
    scale: Scale.SoftChromatic,
    scaleNote: ScaleNote.Ke,
    description: ($) => $.model.initialMartyria.tetraphonicSoftChromatic,
    fthora: Fthora.SoftChromaticThi_Top,
    martyria: ModeSign.AlphaWithDeltaHat,
    note: ModeSign.Ke,
    fthoraAboveNote: Fthora.SoftChromaticThi_Top,
  },
  {
    id: 104,
    mode: 1,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.heirmologicFromDi,
    martyria: ModeSign.AlphaWithDeltaHat,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusKentimaAbove,
  },
  {
    id: 105,
    mode: 1,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.PaHigh,
    description: ($) => $.model.initialMartyria.heptaphonic,
    martyria: ModeSign.AlphaWithDeltaHat,
    quantitativeNeumeRight:
      QuantitativeNeume.OligonPlusHypsiliPlusKentimaVertical,
  },
  {
    id: 106,
    mode: 1,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.PaHigh,
    description: ($) => $.model.initialMartyria.heptaphonic,
    fthora: Fthora.DiatonicPa_Top,
    martyria: ModeSign.AlphaWithDeltaHat,
    quantitativeNeumeRight:
      QuantitativeNeume.OligonPlusHypsiliPlusKentimaVertical,
    fthoraAboveQuantitativeNeumeRight: Fthora.DiatonicPa_Top,
  },
  {
    id: 200,
    mode: 2,
    scale: Scale.SoftChromatic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.sticheraricAndPapadic,
    martyria: ModeSign.SoftChromatic2,
    note: ModeSign.Thi,
    fthoraAboveNote: Fthora.SoftChromaticThi_Top,
  },
  {
    id: 201,
    mode: 2,
    scale: Scale.SoftChromatic,
    scaleNote: ScaleNote.Vou,
    description: ($) => $.model.initialMartyria.heirmologicAndSlowPapadic,
    martyria: ModeSign.SoftChromatic2,
    note: ModeSign.Vou,
    fthoraAboveNote: Fthora.SoftChromaticThi_Top,
  },
  {
    id: 202,
    mode: 2,
    scale: Scale.HardChromatic,
    scaleNote: ScaleNote.Pa,
    description: ($) => $.model.initialMartyria.heirmologicHardChromaticFromPa,
    martyria: ModeSign.SoftChromatic2,
    note: ModeSign.Pa,
    fthoraAboveNote: Fthora.HardChromaticPa_Top,
  },
  {
    id: 203,
    mode: 2,
    scale: Scale.HardChromatic,
    scaleNote: ScaleNote.Vou,
    description: ($) => $.model.initialMartyria.heirmologicHardChromaticFromVou,
    fthora: Fthora.HardChromaticPa_Top,
    martyria: ModeSign.SoftChromatic2,
    note: ModeSign.Vou,
    fthoraAboveNote: Fthora.HardChromaticPa_Top,
  },
  {
    id: 300,
    mode: 3,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ga,
    description: ($) => $.model.initialMartyria.nana,
    martyria: ModeSign.Nana,
    note: ModeSign.Ga,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicGa_Top,
    },
  },
  {
    id: 301,
    mode: 3,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ga,
    description: ($) => $.model.initialMartyria.heirmologicAndSticheraric,
    martyria: ModeSign.NanaOld,
    note: ModeSign.Ga,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicGa_Top,
    },
  },
  {
    id: 302,
    mode: 3,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Pa,
    description: ($) => $.model.initialMartyria.middle,
    martyria: ModeSign.Nana,
    note: ModeSign.Ga,
    quantitativeNeumeRight: QuantitativeNeume.RunningElaphron,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicGa_Top,
    },
  },
  {
    id: 303,
    mode: 3,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ga,
    description: ($) => $.model.initialMartyria.papadic,
    fthora: Fthora.DiatonicNiLow_Top,
    martyria: ModeSign.Nana,
    note: ModeSign.Ga,
    fthoraAboveNote: Fthora.DiatonicNiLow_Top,
  },
  {
    id: 400,
    mode: 4,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.papadicAgia,
    martyria: ModeSign.DeltaWithDeltaHat,
    note: ModeSign.Thi,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicThi_Top,
    },
  },
  {
    id: 401,
    mode: 4,
    scale: Scale.SoftChromatic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.heirmologicSoftChromatic,
    martyria: ModeSign.DeltaWithDeltaHat,
    note: ModeSign.Thi,
    fthoraAboveNote: Fthora.SoftChromaticThi_Top,
  },
  {
    id: 402,
    mode: 4,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Pa,
    description: ($) => $.model.initialMartyria.sticheraric,
    martyria: ModeSign.DeltaWithDeltaHat,
    note: ModeSign.Pa,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicPa_Top,
    },
  },
  {
    id: 403,
    mode: 4,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Vou,
    description: ($) => $.model.initialMartyria.heirmologicLegetos,
    martyria: ModeSign.DeltaWithDeltaHat,
    quantitativeNeumeRight: QuantitativeNeume.RunningElaphron,
  },
  {
    id: 404,
    mode: 4,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Vou,
    description: ($) => $.model.initialMartyria.heirmologicLegetos,
    martyria: ModeSign.Legetos,
    note: ModeSign.Vou,
  },
  {
    id: 405,
    mode: 4,
    scale: Scale.HardChromatic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.heirmologicNenano,
    martyria: ModeSign.DeltaWithDeltaHat,
    note: ModeSign.Thi,
    fthoraAboveNote: Fthora.HardChromaticThi_Top,
  },
  {
    id: 406,
    mode: 4,
    scale: Scale.Kliton,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.kliton,
    martyria: ModeSign.FourthCapital,
    note: ModeSign.Thi,
    fthoraAboveNote: Fthora.Kliton_Top,
  },
  {
    id: 500,
    mode: 5,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Pa,
    description: ($) => $.model.initialMartyria.sticheraricAndPapadic,
    martyria: ModeSign.Alpha,
    note: ModeSign.Pa,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicPa_Top,
    },
  },
  {
    id: 501,
    mode: 5,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ke,
    description: ($) => $.model.initialMartyria.heirmologic,
    martyria: ModeSign.Alpha,
    note: ModeSign.Ke,
    quantitativeNeumeAboveNote: ModeSign.OligonPlusHypsili,
  },
  {
    id: 506,
    mode: 5,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ke,
    description: ($) => $.model.initialMartyria.heirmologicAsFromPa,
    fthora: Fthora.DiatonicPa_Top,
    martyria: ModeSign.Alpha,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusHypsiliRight,
    fthoraAboveQuantitativeNeumeRight: Fthora.DiatonicPa_Top,
  },
  {
    id: 502,
    mode: 5,
    scale: Scale.Spathi,
    scaleNote: ScaleNote.Ke,
    description: ($) => $.model.initialMartyria.spathi,
    martyria: ModeSign.Alpha,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusHypsiliRight,
    fthoraAboveQuantitativeNeumeRight: Fthora.Spathi_Bottom,
  },
  {
    id: 503,
    mode: 5,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.ZoHigh,
    fthora: Fthora.Enharmonic_Top,
    description: ($) => $.model.initialMartyria.pentaphonic,
    martyria: ModeSign.Alpha,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusHypsiliLeft,
    fthoraAboveQuantitativeNeumeRight: Fthora.Enharmonic_Top,
  },
  {
    id: 504,
    mode: 5,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ga,
    fthora: Fthora.Enharmonic_Top,
    description: ($) => $.model.initialMartyria.minorMakamBuselik,
    martyria: ModeSign.Alpha,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusKentima,
    fthoraAboveQuantitativeNeumeRight: Fthora.Enharmonic_Top,
  },
  {
    id: 505,
    mode: 5,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.triphonic,
    martyria: ModeSign.Alpha,
    note: ModeSign.Pa,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusKentimaAbove,
  },
  {
    id: 600,
    mode: 6,
    scale: Scale.HardChromatic,
    scaleNote: ScaleNote.Pa,
    description: ($) => $.model.initialMartyria.sticheraricAndPapadic,
    martyria: ModeSign.SoftChromatic6,
    note: ModeSign.Pa,
    fthoraAboveNote: Fthora.HardChromaticPa_Top,
  },
  {
    id: 601,
    mode: 6,
    scale: Scale.SoftChromatic,
    scaleNote: ScaleNote.Vou,
    description: ($) => $.model.initialMartyria.heirmologicSoftChromaticFromVou,
    martyria: ModeSign.SoftChromatic6,
    note: ModeSign.Vou,
    fthoraAboveNote: Fthora.SoftChromaticThi_Top,
  },
  {
    id: 602,
    mode: 6,
    scale: Scale.SoftChromatic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.heirmologicSoftChromaticFromDi,
    martyria: ModeSign.SoftChromatic6,
    note: ModeSign.Vou,
    fthoraAboveNote: Fthora.SoftChromaticThi_Top,
    quantitativeNeumeRight: QuantitativeNeume.KentemataPlusOligon,
  },
  {
    id: 603,
    mode: 6,
    scale: Scale.HardChromatic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.papadicNenano,
    martyria: ModeSign.SoftChromatic6,
    note: ModeSign.Pa,
    note2: ModeSign.Thi,
    fthoraAboveNote: Fthora.HardChromaticPa_Top,
    quantitativeNeumeAboveNote2: ModeSign.OligonPlusKentima,
  },
  {
    id: 604,
    mode: 6,
    scale: Scale.HardChromatic,
    scaleNote: ScaleNote.PaHigh,
    description: ($) => $.model.initialMartyria.heptaphonicMakamHicazkar,
    martyria: ModeSign.SoftChromatic6,
    note: ModeSign.Pa,
    fthoraAboveNote: Fthora.HardChromaticPa_Top,
    quantitativeNeumeRight:
      QuantitativeNeume.OligonPlusHypsiliPlusKentimaVertical,
    fthoraAboveQuantitativeNeumeRight: Fthora.HardChromaticThi_Top,
  },
  {
    id: 700,
    mode: 7,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ga,
    description: ($) => $.model.initialMartyria.sticheraricAndHeirmologic,
    martyria: ModeSign.VarysZo,
    note: ModeSign.Ga,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicGa_Top,
    },
  },
  {
    id: 701,
    mode: 7,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Zo,
    description: ($) => $.model.initialMartyria.diatonic,
    martyria: ModeSign.VarysZo,
    note: ModeSign.Zo,
  },
  {
    id: 702,
    mode: 7,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Zo,
    description: ($) => $.model.initialMartyria.enharmonic,
    fthora: Fthora.Enharmonic_Top,
    martyria: ModeSign.VarysZo,
    note: ModeSign.Zo,
    fthoraAboveNote: Fthora.Enharmonic_Top,
  },
  {
    id: 703,
    mode: 7,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Thi,
    description: ($) => $.model.initialMartyria.pentaphonicMakamFerahnak,
    fthora: Fthora.DiatonicNiLow_Top,
    martyria: ModeSign.VarysZo,
    note: ModeSign.Zo,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusHypsiliLeft,
    fthoraAboveQuantitativeNeumeRight: Fthora.DiatonicNiLow_Top,
  },
  {
    id: 704,
    mode: 7,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ga,
    description: ($) => $.model.initialMartyria.tetraphonic,
    martyria: ModeSign.VarysZo,
    note: ModeSign.Zo,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusHypsiliRight,
  },
  {
    id: 800,
    mode: 8,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ni,
    description: ($) => $.model.initialMartyria.sticheraricAndPapadic,
    martyria: ModeSign.Delta,
    note: ModeSign.Ni,
    optionalFthoras: {
      fthoraAboveNote: Fthora.DiatonicNiLow_Top,
    },
  },
  {
    id: 801,
    mode: 8,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Ga,
    description: ($) => $.model.initialMartyria.heirmologic,
    fthora: Fthora.DiatonicNiLow_Top,
    martyria: ModeSign.Delta,
    quantitativeNeumeRight: QuantitativeNeume.OligonPlusKentimaAbove,
    fthoraAboveQuantitativeNeumeRight: Fthora.DiatonicNiLow_Top,
  },
  {
    id: 802,
    mode: 8,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Vou,
    description: ($) => $.model.initialMartyria.diphonic,
    martyria: ModeSign.Delta,
    note: ModeSign.Ni,
    quantitativeNeumeRight: QuantitativeNeume.KentemataPlusOligon,
  },
  {
    id: 803,
    mode: 8,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.NiHigh,
    description: ($) => $.model.initialMartyria.heptaphonic,
    martyria: ModeSign.Delta,
    note: ModeSign.Ni,
    quantitativeNeumeRight:
      QuantitativeNeume.OligonPlusHypsiliPlusKentimaVertical,
  },
  {
    id: 804,
    mode: 8,
    scale: Scale.Diatonic,
    scaleNote: ScaleNote.Pa,
    description: ($) => $.model.initialMartyria.sticheraricAndPapadicFromPa,
    fthora: Fthora.DiatonicNiLow_Top,
    martyria: ModeSign.Delta,
    fthoraAboveNote: Fthora.DiatonicNiLow_Top,
    note: ModeSign.Pa,
  },
];
