export enum QuantitativeNeume {
  Ison = 'Ison',

  Oligon = 'Oligon',
  OligonPlusKentimaBelow = 'OligonPlusKentimaBelow',
  OligonPlusKentimaAbove = 'OligonPlusKentimaAbove',
  OligonPlusHypsiliRight = 'OligonPlusHypsiliRight',
  OligonPlusHypsiliLeft = 'OligonPlusHypsiliLeft',
  OligonPlusHypsiliPlusKentimaHorizontal = 'OligonPlusHypsiliPlusKentimaHorizontal',
  OligonPlusHypsiliPlusKentimaVertical = 'OligonPlusHypsiliPlusKentimaVertical',
  OligonPlusDoubleHypsili = 'OligonPlusDoubleHypsili',
  OligonKentimataDoubleYpsili = 'OligonKentimataDoubleYpsili',
  OligonKentimaDoubleYpsiliRight = 'OligonKentimaDoubleYpsiliRight',
  OligonKentimaDoubleYpsiliLeft = 'OligonKentimaDoubleYpsiliLeft',
  OligonTripleYpsili = 'OligonTripleYpsili',
  OligonKentimataTripleYpsili = 'OligonKentimataTripleYpsili',
  OligonKentimaTripleYpsili = 'OligonKentimaTripleYpsili',

  PetastiWithIson = 'PetastiWithIson',
  Petasti = 'Petasti',
  PetastiPlusOligon = 'PetastiPlusOligon',
  PetastiPlusKentimaAbove = 'PetastiPlusKentimaAbove',
  PetastiPlusHypsiliRight = 'PetastiPlusHypsiliRight',
  PetastiPlusHypsiliLeft = 'PetastiPlusHypsiliLeft',
  PetastiPlusHypsiliPlusKentimaHorizontal = 'PetastiPlusHypsiliPlusKentimaHorizontal',
  PetastiPlusHypsiliPlusKentimaVertical = 'PetastiPlusHypsiliPlusKentimaVertical',
  PetastiPlusDoubleHypsili = 'PetastiPlusDoubleHypsili',
  PetastiKentimataDoubleYpsili = 'PetastiKentimataDoubleYpsili',
  PetastiKentimaDoubleYpsiliRight = 'PetastiKentimaDoubleYpsiliRight',
  PetastiKentimaDoubleYpsiliLeft = 'PetastiKentimaDoubleYpsiliLeft',
  PetastiTripleYpsili = 'PetastiTripleYpsili',
  PetastiKentimataTripleYpsili = 'PetastiKentimataTripleYpsili',
  PetastiKentimaTripleYpsili = 'PetastiKentimaTripleYpsili',

  Apostrophos = 'Apostrophos',
  Elaphron = 'Elaphron',
  ElaphronPlusApostrophos = 'ElaphronPlusApostrophos',
  Hamili = 'Hamili',
  HamiliPlusApostrophos = 'HamiliPlusApostrophos',
  HamiliPlusElaphron = 'HamiliPlusElaphron',
  HamiliPlusElaphronPlusApostrophos = 'HamiliPlusElaphronPlusApostrophos',
  DoubleHamili = 'DoubleHamili',
  DoubleHamiliApostrofos = 'DoubleHamiliApostrofos',
  DoubleHamiliElafron = 'DoubleHamiliElafron',
  DoubleHamiliElafronApostrofos = 'DoubleHamiliElafronApostrofos',
  TripleHamili = 'TripleHamili',

  PetastiPlusApostrophos = 'PetastiPlusApostrophos',
  PetastiPlusElaphron = 'PetastiPlusElaphron',
  PetastiPlusElaphronPlusApostrophos = 'PetastiPlusElaphronPlusApostrophos',
  PetastiHamili = 'PetastiHamili',
  PetastiHamiliApostrofos = 'PetastiHamiliApostrofos',
  PetastiHamiliElafron = 'PetastiHamiliElafron',
  PetastiHamiliElafronApostrofos = 'PetastiHamiliElafronApostrofos',
  PetastiDoubleHamili = 'PetastiDoubleHamili',
  PetastiDoubleHamiliApostrofos = 'PetastiDoubleHamiliApostrofos',

  OligonPlusKentemata = 'OligonPlusKentemata',
  KentemataPlusOligon = 'KentemataPlusOligon',
  OligonPlusIsonPlusKentemata = 'OligonPlusIsonPlusKentemata',
  OligonPlusApostrophosPlusKentemata = 'OligonPlusApostrophosPlusKentemata',
  OligonPlusHyporoePlusKentemata = 'OligonPlusHyporoePlusKentemata',
  OligonPlusElaphronPlusKentemata = 'OligonPlusElaphronPlusKentemata',
  OligonPlusElaphronPlusApostrophosPlusKentemata = 'OligonPlusElaphronPlusApostrophosPlusKentemata',
  OligonPlusHamiliPlusKentemata = 'OligonPlusHamiliPlusKentemata',

  RunningElaphron = 'RunningElaphron',
  Hyporoe = 'Hyporoe',
  PetastiPlusRunningElaphron = 'PetastiPlusRunningElaphron',
  PetastiPlusHyporoe = 'PetastiPlusHyporoe',

  OligonPlusIson = 'OligonPlusIson',
  OligonPlusApostrophos = 'OligonPlusApostrophos',
  OligonPlusElaphron = 'OligonPlusElaphron',
  OligonPlusHyporoe = 'OligonPlusHyporoe',
  OligonPlusElaphronPlusApostrophos = 'OligonPlusElaphronPlusApostrophos',
  OligonPlusHamili = 'OligonPlusHamili',

  Kentima = 'Kentima',
  OligonPlusKentima = 'OligonPlusKentima',
  Kentemata = 'Kentemata',

  DoubleApostrophos = 'DoubleApostrophos',
  OligonPlusRunningElaphronPlusKentemata = 'OligonPlusRunningElaphronPlusKentemata',
  IsonPlusApostrophos = 'IsonPlusApostrophos',
  OligonKentimaMiddleKentimata = 'OligonKentimaMiddleKentimata',
  OligonPlusKentemataPlusHypsiliLeft = 'OligonPlusKentemataPlusHypsiliLeft',
  OligonPlusKentemataPlusHypsiliRight = 'OligonPlusKentemataPlusHypsiliRight',

  VareiaDotted = 'VareiaDotted',
  VareiaDotted2 = 'VareiaDotted2',
  VareiaDotted3 = 'VareiaDotted3',
  VareiaDotted4 = 'VareiaDotted4',
  Cross = 'Cross',
  Breath = 'Breath',
}

export enum TimeNeume {
  Klasma_Top = 'Klasma_Top',
  Klasma_Bottom = 'Klasma_Bottom',

  Hapli = 'Hapli',
  Dipli = 'Dipli',
  Tripli = 'Tripli',
  Tetrapli = 'Tetrapli',

  Koronis = 'Koronis',
}

export enum GorgonNeume {
  Gorgon_Top = 'Gorgon_Top',
  Gorgon_Bottom = 'Gorgon_Bottom',
  Digorgon = 'Digorgon',
  Trigorgon = 'Trigorgon',

  GorgonDottedLeft = 'GorgonDottedLeft',
  GorgonDottedRight = 'GorgonDottedRight',

  DigorgonDottedLeft1 = 'DigorgonDottedLeft1',
  DigorgonDottedLeft2 = 'DigorgonDottedLeft2',
  DigorgonDottedRight = 'DigorgonDottedRight',

  TrigorgonDottedLeft1 = 'TrigorgonDottedLeft1',
  TrigorgonDottedLeft2 = 'TrigorgonDottedLeft2',
  TrigorgonDottedRight = 'TrigorgonDottedRight',

  GorgonSecondary = 'GorgonSecondary',
  GorgonDottedLeftSecondary = 'GorgonDottedLeftSecondary',
  GorgonDottedRightSecondary = 'GorgonDottedRightSecondary',

  DigorgonSecondary = 'DigorgonSecondary',
  DigorgonDottedLeft1Secondary = 'DigorgonDottedLeft1Secondary',
  DigorgonDottedLeft2Secondary = 'DigorgonDottedLeft2Secondary',
  DigorgonDottedRightSecondary = 'DigorgonDottedRightSecondary',

  TrigorgonSecondary = 'TrigorgonSecondary',
  TrigorgonDottedLeft1Secondary = 'TrigorgonDottedLeft1Secondary',
  TrigorgonDottedLeft2Secondary = 'TrigorgonDottedLeft2Secondary',
  TrigorgonDottedRightSecondary = 'TrigorgonDottedRightSecondary',

  Argon = 'Argon',
  Hemiolion = 'Hemiolion',
  Diargon = 'Diargon',
}

export enum VocalExpressionNeume {
  Vareia = 'Vareia',
  HomalonConnecting = 'HomalonConnecting',
  Homalon = 'Homalon',
  Antikenoma = 'Antikenoma',
  Psifiston = 'Psifiston',
  PsifistonSlanted = 'PsifistonSlanted',
  Heteron = 'Heteron',
  HeteronConnecting = 'HeteronConnecting',
  HeteronConnectingLong = 'HeteronConnectingLong',
  Endofonon = 'Endofonon',
  Cross_Top = 'Cross_Top',
}

export enum RootSign {
  Delta = 'Delta',
  Alpha = 'Alpha',
  Legetos = 'Legetos',
  Nana = 'Nana',
  Tilt = 'Tilt',
  TiltLow = 'TiltLow',
  Zo = 'Varys',
  ZoLow = 'VarysLow',
  Squiggle = 'Squiggle',
  SquiggleLow = 'SquiggleLow',
  Zygos = 'Zygos',
  ZygosLow = 'ZygosLow',
  SoftChromaticSquiggle = 'SoftChromaticSquiggle',
  SoftChromaticSquiggleLow = 'SoftChromaticSquiggleLow',
  DeltaDotted = 'DeltaDotted',
  DeltaDottedLow = 'DeltaDottedLow',
  AlphaDotted = 'AlphaDotted',
  AlphaDottedLow = 'AlphaDottedLow',
  SoftChromaticPaRootSign = 'SoftChromaticPaRootSign',
  SoftChromaticPaRootSignLow = 'SoftChromaticPaRootSignLow',
  NanaLow = 'NanaLow',
  DeltaLow = 'DeltaLow',
  AlphaLow = 'AlphaLow',
  LegetosLow = 'LegetosLow',
}

export enum Note {
  ZoLow = 'ZoLow',
  NiLow = 'NiLow',
  PaLow = 'PaLow',
  VouLow = 'VouLow',
  GaLow = 'GaLow',
  ThiLow = 'ThiLow',
  KeLow = 'KeLow',
  Zo = 'Zo',
  Ni = 'Ni',
  Pa = 'Pa',
  Vou = 'Vou',
  Ga = 'Ga',
  Thi = 'Thi',
  Ke = 'Ke',
  ZoHigh = 'ZoHigh',
  NiHigh = 'NiHigh',
  PaHigh = 'PaHigh',
  VouHigh = 'VouHigh',
  GaHigh = 'GaHigh',
  ThiHigh = 'ThiHigh',
  KeHigh = 'KeHigh',
}

export enum TempoSign {
  VerySlow = 'VerySlow',
  Slower = 'Slower',
  Slow = 'Slow',
  Medium = 'Medium',
  Moderate = 'Moderate',
  Quick = 'Quick',
  Quicker = 'Quicker',
  VeryQuick = 'VeryQuick',

  VerySlowAbove = 'VerySlowAbove',
  SlowerAbove = 'SlowerAbove',
  SlowAbove = 'SlowAbove',
  MediumAbove = 'MediumAbove',
  ModerateAbove = 'ModerateAbove',
  QuickAbove = 'QuickAbove',
  QuickerAbove = 'QuickerAbove',
  VeryQuickAbove = 'VeryQuickAbove',
}

export enum ModeSign {
  Ni = 'ModeSign.Ni',
  Pa = 'ModeSign.Pa',
  Vou = 'ModeSign.Vou',
  Ga = 'ModeSign.Ga',
  Thi = 'ModeSign.Thi',
  Ke = 'ModeSign.Ke',
  Zo = 'ModeSign.Zo',
  Ekhos = 'ModeSign.Ekhos',
  Plagal = 'ModeSign.Plagal',
  First = 'ModeSign.First',
  FirstCapital = 'ModeSign.FirstCapital',
  Second = 'ModeSign.Second',
  SecondCapital = 'ModeSign.SecondCapital',
  Third = 'ModeSign.Third',
  ThirdCapital = 'ModeSign.ThirdCapital',
  Fourth = 'ModeSign.Fourth',
  FourthCapital = 'ModeSign.FourthCapital',
  Varys = 'ModeSign.Varys',
  Alpha = 'ModeSign.Alpha',
  AlphaWithDeltaHat = 'ModeSign.AlphaWithDeltaHat',
  AlphaWithHypsili = 'ModeSign.AlphaWithHypsili',
  SoftChromatic2 = 'ModeSign.SoftChromatic2',
  SoftChromatic6 = 'ModeSign.SoftChromatic6',
  Nana = 'ModeSign.Nana',
  VarysZo = 'ModeSign.VarysZo',
  Delta = 'ModeSign.Delta',
  DeltaWithDeltaHat = 'ModeSign.DeltaWithDeltaHat',
  DeltaWithHypsili = 'ModeSign.DeltaWithHypsili',
  NanaOld = 'ModeSign.NanaOld',
  Legetos = 'ModeSign.Legetos',
  ElaphronPlusApostrophos = 'ModeSign.ElaphronPlusApostrophos',
  Elaphron = 'ModeSign.Elaphron',
  OligonPlusKentima = 'ModeSign.OligonPlusKentima',
  OligonPlusHypsili = 'ModeSign.OligonPlusHypsili',
}

export enum Fthora {
  DiatonicNiLow_Top = 'DiatonicNiLow_Top',
  DiatonicPa_Top = 'DiatonicPa_Top',
  DiatonicVou_Top = 'DiatonicVou_Top',
  DiatonicGa_Top = 'DiatonicGa_Top',
  DiatonicThi_Top = 'DiatonicThi_Top',
  DiatonicKe_Top = 'DiatonicKe_Top',
  DiatonicZo_Top = 'DiatonicZo_Top',
  DiatonicNiHigh_Top = 'DiatonicNiHigh_Top',
  HardChromaticPa_Top = 'HardChromaticPa_Top',
  HardChromaticThi_Top = 'HardChromaticThi_Top',
  SoftChromaticPa_Top = 'SoftChromaticPa_Top',
  SoftChromaticThi_Top = 'SoftChromaticThi_Top',
  Enharmonic_Top = 'Enharmonic_Top',
  Zygos_Top = 'Zygos_Top',
  Kliton_Top = 'Kliton_Top',
  Spathi_Top = 'Spathi_Top',

  DiatonicNiLow_TopSecondary = 'DiatonicNiLow_TopSecondary',
  DiatonicPa_TopSecondary = 'DiatonicPa_TopSecondary',
  DiatonicVou_TopSecondary = 'DiatonicVou_TopSecondary',
  DiatonicGa_TopSecondary = 'DiatonicGa_TopSecondary',
  DiatonicThi_TopSecondary = 'DiatonicThi_TopSecondary',
  DiatonicKe_TopSecondary = 'DiatonicKe_TopSecondary',
  DiatonicZo_TopSecondary = 'DiatonicZo_TopSecondary',
  DiatonicNiHigh_TopSecondary = 'DiatonicNiHigh_TopSecondary',
  HardChromaticPa_TopSecondary = 'HardChromaticPa_TopSecondary',
  HardChromaticThi_TopSecondary = 'HardChromaticThi_TopSecondary',
  SoftChromaticPa_TopSecondary = 'SoftChromaticPa_TopSecondary',
  SoftChromaticThi_TopSecondary = 'SoftChromaticThi_TopSecondary',
  Enharmonic_TopSecondary = 'Enharmonic_TopSecondary',
  Zygos_TopSecondary = 'Zygos_TopSecondary',
  Kliton_TopSecondary = 'Kliton_TopSecondary',
  Spathi_TopSecondary = 'Spathi_TopSecondary',

  DiatonicNiLow_TopTertiary = 'DiatonicNiLow_TopTertiary',
  DiatonicPa_TopTertiary = 'DiatonicPa_TopTertiary',
  DiatonicVou_TopTertiary = 'DiatonicVou_TopTertiary',
  DiatonicGa_TopTertiary = 'DiatonicGa_TopTertiary',
  DiatonicThi_TopTertiary = 'DiatonicThi_TopTertiary',
  DiatonicKe_TopTertiary = 'DiatonicKe_TopTertiary',
  DiatonicZo_TopTertiary = 'DiatonicZo_TopTertiary',
  DiatonicNiHigh_TopTertiary = 'DiatonicNiHigh_TopTertiary',
  HardChromaticPa_TopTertiary = 'HardChromaticPa_TopTertiary',
  HardChromaticThi_TopTertiary = 'HardChromaticThi_TopTertiary',
  SoftChromaticPa_TopTertiary = 'SoftChromaticPa_TopTertiary',
  SoftChromaticThi_TopTertiary = 'SoftChromaticThi_TopTertiary',
  Enharmonic_TopTertiary = 'Enharmonic_TopTertiary',
  Zygos_TopTertiary = 'Zygos_TopTertiary',
  Kliton_TopTertiary = 'Kliton_TopTertiary',
  Spathi_TopTertiary = 'Spathi_TopTertiary',

  DiatonicNiLow_Bottom = 'DiatonicNiLow_Bottom',
  DiatonicPa_Bottom = 'DiatonicPa_Bottom',
  DiatonicVou_Bottom = 'DiatonicVou_Bottom',
  DiatonicGa_Bottom = 'DiatonicGa_Bottom',
  DiatonicThi_Bottom = 'DiatonicThi_Bottom',
  DiatonicKe_Bottom = 'DiatonicKe_Bottom',
  DiatonicZo_Bottom = 'DiatonicZo_Bottom',
  DiatonicNiHigh_Bottom = 'DiatonicNiHigh_Bottom',
  HardChromaticPa_Bottom = 'HardChromaticPa_Bottom',
  HardChromaticThi_Bottom = 'HardChromaticThi_Bottom',
  SoftChromaticPa_Bottom = 'SoftChromaticPa_Bottom',
  SoftChromaticThi_Bottom = 'SoftChromaticThi_Bottom',
  Enharmonic_Bottom = 'Enharmonic_Bottom',
  Zygos_Bottom = 'Zygos_Bottom',
  Kliton_Bottom = 'Kliton_Bottom',
  Spathi_Bottom = 'Spathi_Bottom',

  GeneralSharp_Top = 'GeneralSharp_Top',
  GeneralSharp_TopSecondary = 'GeneralSharp_TopSecondary',
  GeneralSharp_TopTertiary = 'GeneralSharp_TopTertiary',
  GeneralSharp_Bottom = 'GeneralSharp_Bottom',

  GeneralFlat_Top = 'GeneralFlat_Top',
  GeneralFlat_TopSecondary = 'GeneralFlat_TopSecondary',
  GeneralFlat_TopTertiary = 'GeneralFlat_TopTertiary',
  GeneralFlat_Bottom = 'GeneralFlat_Bottom',
}

export enum Accidental {
  Sharp_2_Left = 'Sharp_2_Left',
  Sharp_4_Left = 'Sharp_4_Left',
  Sharp_6_Left = 'Sharp_6_Left',
  Sharp_8_Left = 'Sharp_8_Left',

  Sharp_2_LeftSecondary = 'Sharp_2_LeftSecondary',
  Sharp_4_LeftSecondary = 'Sharp_4_LeftSecondary',
  Sharp_6_LeftSecondary = 'Sharp_6_LeftSecondary',
  Sharp_8_LeftSecondary = 'Sharp_8_LeftSecondary',

  Sharp_2_LeftTertiary = 'Sharp_2_LeftTertiary',
  Sharp_4_LeftTertiary = 'Sharp_4_LeftTertiary',
  Sharp_6_LeftTertiary = 'Sharp_6_LeftTertiary',
  Sharp_8_LeftTertiary = 'Sharp_8_LeftTertiary',

  Flat_2_Right = 'Flat_2_Right',
  Flat_4_Right = 'Flat_4_Right',
  Flat_6_Right = 'Flat_6_Right',
  Flat_8_Right = 'Flat_8_Right',

  Flat_2_RightSecondary = 'Flat_2_RightSecondary',
  Flat_4_RightSecondary = 'Flat_4_RightSecondary',
  Flat_6_RightSecondary = 'Flat_6_RightSecondary',
  Flat_8_RightSecondary = 'Flat_8_RightSecondary',

  Flat_2_RightTertiary = 'Flat_2_RightTertiary',
  Flat_4_RightTertiary = 'Flat_4_RightTertiary',
  Flat_6_RightTertiary = 'Flat_6_RightTertiary',
  Flat_8_RightTertiary = 'Flat_8_RightTertiary',
}

export enum MeasureBar {
  MeasureBarRight = 'MeasureBarRight',
  MeasureBarTop = 'MeasureBarTop',
  MeasureBarDouble = 'MeasureBarDouble',
  MeasureBarShortDouble = 'MeasureBarShortDouble',
  MeasureBarTheseos = 'MeasureBarTheseos',
  MeasureBarShortTheseos = 'MeasureBarShortTheseos',
  MeasureBarRightAbove = 'MeasureBarRightAbove',
  MeasureBarTopAbove = 'MeasureBarTopAbove',
  MeasureBarDoubleAbove = 'MeasureBarDoubleAbove',
  MeasureBarShortDoubleAbove = 'MeasureBarShortDoubleAbove',
  MeasureBarTheseosAbove = 'MeasureBarTheseosAbove',
  MeasureBarShortTheseosAbove = 'MeasureBarShortTheseosAbove',
}

export enum MeasureNumber {
  Two = 'Two',
  Three = 'Three',
  Four = 'Four',
  Five = 'Five',
  Six = 'Six',
  Seven = 'Seven',
  Eight = 'Eight',
}

export enum NoteIndicator {
  Ni = 'NoteIndicator.Ni',
  Pa = 'NoteIndicator.Pa',
  Vou = 'NoteIndicator.Vou',
  Ga = 'NoteIndicator.Ga',
  Thi = 'NoteIndicator.Thi',
  Ke = 'NoteIndicator.Ke',
  Zo = 'NoteIndicator.Zo',
}

export enum Ison {
  Unison = 'Ison.Unison',
  ThiLow = 'Ison.ThiLow',
  KeLow = 'Ison.KeLow',
  Zo = 'Ison.Zo',
  Ni = 'Ison.Ni',
  Pa = 'Ison.Pa',
  Vou = 'Ison.Vou',
  Ga = 'Ison.Ga',
  Thi = 'Ison.Thi',
  Ke = 'Ison.Ke',
  ZoHigh = 'Ison.ZoHigh',
}

export enum Tie {
  YfenAbove = 'YfenAbove',
  YfenBelow = 'YfenBelow',
}

export enum UnicodeNeume {
  Uni1d000 = 'uni1d000',
  Uni1d001 = 'uni1d001',
  Uni1d002 = 'uni1d002',
  Uni1d003 = 'uni1d003',
  Uni1d004 = 'uni1d004',
  Uni1d005 = 'uni1d005',
  Uni1d006 = 'uni1d006',
  Uni1d007 = 'uni1d007',
  Uni1d008 = 'uni1d008',
  Uni1d009 = 'uni1d009',
  Uni1d00a = 'uni1d00a',
  Uni1d00b = 'uni1d00b',
  Uni1d00c = 'uni1d00c',
  Uni1d00d = 'uni1d00d',
  Uni1d00e = 'uni1d00e',
  Uni1d00f = 'uni1d00f',
  Uni1d010 = 'uni1d010',
  Uni1d011 = 'uni1d011',
  Uni1d012 = 'uni1d012',
  Uni1d013 = 'uni1d013',
  Uni1d014 = 'uni1d014',
  Uni1d015 = 'uni1d015',
  Uni1d016 = 'uni1d016',
  Uni1d017 = 'uni1d017',
  Uni1d018 = 'uni1d018',
  Uni1d019 = 'uni1d019',
  Uni1d01a = 'uni1d01a',
  Uni1d01b = 'uni1d01b',
  Uni1d01c = 'uni1d01c',
  Uni1d01d = 'uni1d01d',
  Uni1d01e = 'uni1d01e',
  Uni1d01f = 'uni1d01f',
  Uni1d020 = 'uni1d020',
  Uni1d021 = 'uni1d021',
  Uni1d022 = 'uni1d022',
  Uni1d023 = 'uni1d023',
  Uni1d024 = 'uni1d024',
  Uni1d025 = 'uni1d025',
  Uni1d026 = 'uni1d026',
  Uni1d027 = 'uni1d027',
  Uni1d028 = 'uni1d028',
  Uni1d029 = 'uni1d029',
  Uni1d02a = 'uni1d02a',
  Uni1d02b = 'uni1d02b',
  Uni1d02c = 'uni1d02c',
  Uni1d02d = 'uni1d02d',
  Uni1d02e = 'uni1d02e',
  Uni1d02f = 'uni1d02f',
  Uni1d030 = 'uni1d030',
  Uni1d031 = 'uni1d031',
  Uni1d032 = 'uni1d032',
  Uni1d033 = 'uni1d033',
  Uni1d034 = 'uni1d034',
  Uni1d035 = 'uni1d035',
  Uni1d036 = 'uni1d036',
  Uni1d037 = 'uni1d037',
  Uni1d038 = 'uni1d038',
  Uni1d039 = 'uni1d039',
  Uni1d03a = 'uni1d03a',
  Uni1d03b = 'uni1d03b',
  Uni1d03c = 'uni1d03c',
  Uni1d03d = 'uni1d03d',
  Uni1d03e = 'uni1d03e',
  Uni1d03f = 'uni1d03f',
  Uni1d040 = 'uni1d040',
  Uni1d041 = 'uni1d041',
  Uni1d042 = 'uni1d042',
  Uni1d043 = 'uni1d043',
  Uni1d044 = 'uni1d044',
  Uni1d045 = 'uni1d045',
  Uni1d046 = 'uni1d046',
  Uni1d047 = 'uni1d047',
  Uni1d048 = 'uni1d048',
  Uni1d049 = 'uni1d049',
  Uni1d04a = 'uni1d04a',
  Uni1d04b = 'uni1d04b',
  Uni1d04c = 'uni1d04c',
  Uni1d04d = 'uni1d04d',
  Uni1d04e = 'uni1d04e',
  Uni1d04f = 'uni1d04f',
  Uni1d050 = 'uni1d050',
  Uni1d051 = 'uni1d051',
  Uni1d052 = 'uni1d052',
  Uni1d053 = 'uni1d053',
  Uni1d054 = 'uni1d054',
  Uni1d055 = 'uni1d055',
  Uni1d056 = 'uni1d056',
  Uni1d057 = 'uni1d057',
  Uni1d058 = 'uni1d058',
  Uni1d059 = 'uni1d059',
  Uni1d05a = 'uni1d05a',
  Uni1d05b = 'uni1d05b',
  Uni1d05c = 'uni1d05c',
  Uni1d05d = 'uni1d05d',
  Uni1d05e = 'uni1d05e',
  Uni1d05f = 'uni1d05f',
  Uni1d060 = 'uni1d060',
  Uni1d061 = 'uni1d061',
  Uni1d062 = 'uni1d062',
  Uni1d063 = 'uni1d063',
  Uni1d064 = 'uni1d064',
  Uni1d065 = 'uni1d065',
  Uni1d066 = 'uni1d066',
  Uni1d067 = 'uni1d067',
  Uni1d068 = 'uni1d068',
  Uni1d069 = 'uni1d069',
  Uni1d06a = 'uni1d06a',
  Uni1d06b = 'uni1d06b',
  Uni1d06c = 'uni1d06c',
  Uni1d06d = 'uni1d06d',
  Uni1d06e = 'uni1d06e',
  Uni1d06f = 'uni1d06f',
  Uni1d070 = 'uni1d070',
  Uni1d071 = 'uni1d071',
  Uni1d072 = 'uni1d072',
  Uni1d073 = 'uni1d073',
  Uni1d074 = 'uni1d074',
  Uni1d075 = 'uni1d075',
  Uni1d076 = 'uni1d076',
  Uni1d077 = 'uni1d077',
  Uni1d078 = 'uni1d078',
  Uni1d079 = 'uni1d079',
  Uni1d07a = 'uni1d07a',
  Uni1d07b = 'uni1d07b',
  Uni1d07c = 'uni1d07c',
  Uni1d07d = 'uni1d07d',
  Uni1d07e = 'uni1d07e',
  Uni1d07f = 'uni1d07f',
  Uni1d080 = 'uni1d080',
  Uni1d081 = 'uni1d081',
  Uni1d082 = 'uni1d082',
  Uni1d083 = 'uni1d083',
  Uni1d084 = 'uni1d084',
  Uni1d085 = 'uni1d085',
  Uni1d086 = 'uni1d086',
  Uni1d087 = 'uni1d087',
  Uni1d088 = 'uni1d088',
  Uni1d089 = 'uni1d089',
  Uni1d08a = 'uni1d08a',
  Uni1d08b = 'uni1d08b',
  Uni1d08c = 'uni1d08c',
  Uni1d08d = 'uni1d08d',
  Uni1d08e = 'uni1d08e',
  Uni1d08f = 'uni1d08f',
  Uni1d090 = 'uni1d090',
  Uni1d091 = 'uni1d091',
  Uni1d092 = 'uni1d092',
  Uni1d093 = 'uni1d093',
  Uni1d094 = 'uni1d094',
  Uni1d095 = 'uni1d095',
  Uni1d096 = 'uni1d096',
  Uni1d097 = 'uni1d097',
  Uni1d098 = 'uni1d098',
  Uni1d099 = 'uni1d099',
  Uni1d09a = 'uni1d09a',
  Uni1d09b = 'uni1d09b',
  Uni1d09c = 'uni1d09c',
  Uni1d09d = 'uni1d09d',
  Uni1d09e = 'uni1d09e',
  Uni1d09f = 'uni1d09f',
  Uni1d0a0 = 'uni1d0a0',
  Uni1d0a1 = 'uni1d0a1',
  Uni1d0a2 = 'uni1d0a2',
  Uni1d0a3 = 'uni1d0a3',
  Uni1d0a4 = 'uni1d0a4',
  Uni1d0a5 = 'uni1d0a5',
  Uni1d0a6 = 'uni1d0a6',
  Uni1d0a7 = 'uni1d0a7',
  Uni1d0a8 = 'uni1d0a8',
  Uni1d0a9 = 'uni1d0a9',
  Uni1d0aa = 'uni1d0aa',
  Uni1d0ab = 'uni1d0ab',
  Uni1d0ac = 'uni1d0ac',
  Uni1d0ad = 'uni1d0ad',
  Uni1d0ae = 'uni1d0ae',
  Uni1d0af = 'uni1d0af',
  Uni1d0b0 = 'uni1d0b0',
  Uni1d0b1 = 'uni1d0b1',
  Uni1d0b2 = 'uni1d0b2',
  Uni1d0b3 = 'uni1d0b3',
  Uni1d0b4 = 'uni1d0b4',
  Uni1d0b5 = 'uni1d0b5',
  Uni1d0b6 = 'uni1d0b6',
  Uni1d0b7 = 'uni1d0b7',
  Uni1d0b8 = 'uni1d0b8',
  Uni1d0b9 = 'uni1d0b9',
  Uni1d0ba = 'uni1d0ba',
  Uni1d0bb = 'uni1d0bb',
  Uni1d0bc = 'uni1d0bc',
  Uni1d0bd = 'uni1d0bd',
  Uni1d0be = 'uni1d0be',
  Uni1d0bf = 'uni1d0bf',
  Uni1d0c0 = 'uni1d0c0',
  Uni1d0c1 = 'uni1d0c1',
  Uni1d0c2 = 'uni1d0c2',
  Uni1d0c3 = 'uni1d0c3',
  Uni1d0c4 = 'uni1d0c4',
  Uni1d0c5 = 'uni1d0c5',
  Uni1d0c6 = 'uni1d0c6',
  Uni1d0c7 = 'uni1d0c7',
  Uni1d0c8 = 'uni1d0c8',
  Uni1d0c9 = 'uni1d0c9',
  Uni1d0ca = 'uni1d0ca',
  Uni1d0cb = 'uni1d0cb',
  Uni1d0cc = 'uni1d0cc',
  Uni1d0cd = 'uni1d0cd',
  Uni1d0ce = 'uni1d0ce',
  Uni1d0cf = 'uni1d0cf',
  Uni1d0d0 = 'uni1d0d0',
  Uni1d0d1 = 'uni1d0d1',
  Uni1d0d2 = 'uni1d0d2',
  Uni1d0d3 = 'uni1d0d3',
  Uni1d0d4 = 'uni1d0d4',
  Uni1d0d5 = 'uni1d0d5',
  Uni1d0d6 = 'uni1d0d6',
  Uni1d0d7 = 'uni1d0d7',
  Uni1d0d8 = 'uni1d0d8',
  Uni1d0d9 = 'uni1d0d9',
  Uni1d0da = 'uni1d0da',
  Uni1d0db = 'uni1d0db',
  Uni1d0dc = 'uni1d0dc',
  Uni1d0dd = 'uni1d0dd',
  Uni1d0de = 'uni1d0de',
  Uni1d0df = 'uni1d0df',
  Uni1d0e0 = 'uni1d0e0',
  Uni1d0e1 = 'uni1d0e1',
  Uni1d0e2 = 'uni1d0e2',
  Uni1d0e3 = 'uni1d0e3',
  Uni1d0e4 = 'uni1d0e4',
  Uni1d0e5 = 'uni1d0e5',
  Uni1d0e6 = 'uni1d0e6',
  Uni1d0e7 = 'uni1d0e7',
  Uni1d0e8 = 'uni1d0e8',
  Uni1d0e9 = 'uni1d0e9',
  Uni1d0ea = 'uni1d0ea',
  Uni1d0eb = 'uni1d0eb',
  Uni1d0ec = 'uni1d0ec',
  Uni1d0ed = 'uni1d0ed',
  Uni1d0ee = 'uni1d0ee',
  Uni1d0ef = 'uni1d0ef',
  Uni1d0f0 = 'uni1d0f0',
  Uni1d0f1 = 'uni1d0f1',
  Uni1d0f2 = 'uni1d0f2',
  Uni1d0f3 = 'uni1d0f3',
  Uni1d0f4 = 'uni1d0f4',
  Uni1d0f5 = 'uni1d0f5',
  Uni1d0f6 = 'uni1d0f6',
  Uni1d0f7 = 'uni1d0f7',
  Uni1d0f8 = 'uni1d0f8',
  Uni1d0f9 = 'uni1d0f9',
  Uni1d0fa = 'uni1d0fa',
  Uni1d0fb = 'uni1d0fb',
  Uni1d0fc = 'uni1d0fc',
  Uni1d0fd = 'uni1d0fd',
  Uni1d0fe = 'uni1d0fe',
  Uni1d0ff = 'uni1d0ff',
}

export enum NeumeSelection {
  Primary = 'Primary',
  Secondary = 'Secondary',
  Tertiary = 'Tertiary',
}

export type Neume =
  | QuantitativeNeume
  | TimeNeume
  | GorgonNeume
  | VocalExpressionNeume
  | Fthora
  | Accidental
  | TempoSign
  | Note
  | RootSign
  | ModeSign
  | MeasureBar
  | MeasureNumber
  | NoteIndicator
  | Ison
  | Tie
  | UnicodeNeume;

export const petastiNeumes: ReadonlyArray<QuantitativeNeume> = [
  QuantitativeNeume.PetastiWithIson,
  QuantitativeNeume.Petasti,
  QuantitativeNeume.PetastiPlusOligon,
  QuantitativeNeume.PetastiPlusKentimaAbove,
  QuantitativeNeume.PetastiPlusHypsiliRight,
  QuantitativeNeume.PetastiPlusHypsiliLeft,
  QuantitativeNeume.PetastiPlusHypsiliPlusKentimaHorizontal,
  QuantitativeNeume.PetastiPlusHypsiliPlusKentimaVertical,
  QuantitativeNeume.PetastiPlusDoubleHypsili,
  QuantitativeNeume.PetastiPlusApostrophos,
  QuantitativeNeume.PetastiPlusElaphron,
  QuantitativeNeume.PetastiPlusElaphronPlusApostrophos,
  QuantitativeNeume.PetastiPlusHyporoe,
  QuantitativeNeume.PetastiPlusRunningElaphron,
];

export const oligonNeumes: ReadonlyArray<QuantitativeNeume> = [
  QuantitativeNeume.Oligon,
  QuantitativeNeume.OligonPlusApostrophos,
  QuantitativeNeume.OligonPlusApostrophosPlusKentemata,
  QuantitativeNeume.OligonPlusDoubleHypsili,
  QuantitativeNeume.OligonPlusHyporoePlusKentemata,
  QuantitativeNeume.OligonPlusElaphronPlusApostrophosPlusKentemata,
  QuantitativeNeume.OligonPlusElaphronPlusKentemata,
  QuantitativeNeume.OligonPlusHamiliPlusKentemata,
  QuantitativeNeume.OligonPlusHypsiliLeft,
  QuantitativeNeume.OligonPlusHypsiliPlusKentimaHorizontal,
  QuantitativeNeume.OligonPlusHypsiliPlusKentimaVertical,
  QuantitativeNeume.OligonPlusHypsiliRight,
  QuantitativeNeume.OligonPlusIsonPlusKentemata,
  QuantitativeNeume.OligonPlusKentemata,
  QuantitativeNeume.OligonKentimaMiddleKentimata,
  QuantitativeNeume.OligonPlusKentemataPlusHypsiliLeft,
  QuantitativeNeume.OligonPlusKentemataPlusHypsiliRight,
  QuantitativeNeume.OligonPlusKentima,
  QuantitativeNeume.OligonPlusKentimaAbove,
  QuantitativeNeume.OligonPlusKentimaBelow,
  QuantitativeNeume.OligonPlusRunningElaphronPlusKentemata,
  QuantitativeNeume.KentemataPlusOligon,
  QuantitativeNeume.PetastiPlusOligon,
];

export const restNeumes: ReadonlyArray<QuantitativeNeume> = [
  QuantitativeNeume.Breath,
  QuantitativeNeume.Cross,
  QuantitativeNeume.VareiaDotted,
  QuantitativeNeume.VareiaDotted2,
  QuantitativeNeume.VareiaDotted3,
  QuantitativeNeume.VareiaDotted4,
];
