import 'ckeditor5/ckeditor5.css';

import {
  Alignment,
  AutoImage,
  AutoLink,
  Base64UploadAdapter,
  Bold,
  Essentials,
  FindAndReplace,
  FontColor,
  FontFamily,
  FontSize,
  GeneralHtmlSupport,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  InlineEditor as InlineEditorBase,
  Italic,
  Link,
  List,
  Paragraph,
  PasteFromOffice,
  RemoveFormat,
  SelectAll,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextTransformation,
  Underline,
  Undo,
} from 'ckeditor5';

import FontFamilyDropdown from './ckeditor-plugins/fontfamilydropdown/fontfamilydropdown';
import FontSizeDropdown from './ckeditor-plugins/fontsizedropdown/fontsizedropdown';
import InsertNeume from './ckeditor-plugins/insertneume/insertneume';

export default class InlineEditor extends InlineEditorBase {}

InlineEditor.builtinPlugins = [
  Alignment,
  AutoImage,
  AutoLink,
  Base64UploadAdapter,
  Bold,
  Essentials,
  FindAndReplace,
  FontColor,
  FontFamily,
  FontFamilyDropdown,
  FontSize,
  FontSizeDropdown,
  GeneralHtmlSupport,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  InsertNeume,
  Italic,
  Link,
  List,
  Paragraph,
  PasteFromOffice,
  RemoveFormat,
  SelectAll,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextTransformation,
  Underline,
  Undo,
];

InlineEditor.defaultConfig = {
  toolbar: {
    items: [
      'fontFamilyDropdown',
      'fontSizeDropdown',
      '|',
      'bold',
      'italic',
      'underline',
      '|',
      {
        label: 'Alignment',
        icon: 'alignLeft',
        items: [
          'alignment:left',
          'alignment:center',
          'alignment:right',
          'alignment:justify',
        ],
      },
      'fontColor',
      '|',
      {
        label: 'Insert',
        icon: 'plus',
        items: [
          'bulletedList',
          'numberedList',
          'outdent',
          'indent',
          'subscript',
          'superscript',
          'link',
          'imageUpload',
          'insertTable',
          'insertNeume',
          'insertMartyria',
          'insertPlagal',
        ],
      },
      '|',
      'undo',
      'redo',
      '|',
      {
        label: 'Tools',
        icon: 'threeVerticalDots',
        items: ['findAndReplace', 'selectAll', 'removeFormat'],
      },
      '|',
    ],
    shouldNotGroupWhenFull: true,
  },
  language: 'en',
  image: {
    toolbar: [
      'imageTextAlternative',
      'toggleImageCaption',
      'imageStyle:inline',
      'imageStyle:block',
      'imageStyle:side',
    ],
  },
  table: {
    contentToolbar: [
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      'tableProperties',
      'tableCellProperties',
    ],
  },
  htmlSupport: {
    allow: [
      {
        name: 'span',
        styles: true,
        attributes: true,
      },
    ],
  },
};
